### PR TITLE
Use a label for classes rather than class name. Improve the help text.

### PR DESCRIPTION
**Pull request by herbdool**
Addresses #14 and #12 (partly)

### CODE REVIEW

**Comment by herbdool** [comment]
@Graham-72 if you've got a moment can you check this PR? I've tried to improve the help text and I've also added an approach for displaying the module names and descriptions instead of the classes. It works fairly well, though I added a workaround for the core classes (default and testing) since they are in the same module.

**Comment by Graham-72** [comment]
@herbdool I think this is a big improvement, thank you. I have a couple of suggestions.

Instead of 'Theme to render the emails' it might say 'Theme to render HTML emails', and in the description for this say 'Select the theme that will be used to render HTML emails.'

In the custom settings section I think it might be a bit clearer if it read 
'Each module that sends out email can set IDs that identify the class of email being sent and hence the methods to be used for sending. Here you can set the methods to be used for each such identifier. For example, you might want to set up contact form emails differently from event calendar notifications. An identifier is composed of a module and an optional key. To decide which methods .......'

**Comment by herbdool** [comment]
@Graham-72 thanks for the review. I've changed the help text a bit, inspired by your suggestions. And I've merged.

**Comment by Graham-72** [comment]
@herbdool this is now very good, thank you.

Have you any idea why the BD project installer is showing v1.1.0 as the primary choice and not this latest v3.0.2, which it shows as an alternative? We ought to get this changed, shouldn't we?

**Comment by herbdool** [comment]
Thanks @Graham-72. I think it will require someone with higher permissions on the website. @jenlampton or @quicksketch? It might be because I changed the default branch so it matches the tag.

**Pull request merged**
